###
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: thomaslacaze/freebox-security-api
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

- name: publish readme
  image: thomaslacaze/dockerhub-description:2.4.1
  pull: always
  settings:
    repository: thomaslacaze/freebox-security-api
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    readme: /drone/src/README.md
  when:
    branch:
    - master
    - main

- name: publish develop
  image: plugins/docker
  settings:
    tags: develop
    repo: thomaslacaze/freebox-security-api
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - develop
###


